### ISSUE TITLE
New 2 Anticheats

### ISSUE THREAD

**Issue by MinecraftUserHAN1110** [ManInMyVan/Minecraft-Anticheat-List#2]
### Anticheat Name

Frequency+ / AntiCheatUnit

### Cost

Free

### Edition

Java

### Platform

Bukkit (or a fork)

### Status

Inactive (Explicitly Inactive)

### Versions

Frequency+ 1.2 / AntiCheatUnit 1.2.1

### Links

Check my github

### Rating Percentage

Idk

### Number of ratings

Idk

### Before submitting an anticheat

- [x] This anticheat wasn't already submitted (I have searched anticheat submitions on GitHub).

**Comment by MinecraftUserHAN1110** [comment]
Note: they are mine. Not hypixel's or another people'

**Comment by ManInMyVan** [comment]
So I just made the versions section specify it's for Minecraft version, and I want clarification on whether you meant Minecraft version, or anticheat version.

**Comment by ManInMyVan** [comment]
I have decided not to add AntiCheatUnit due to it being an addon for Matrix
