### ISSUE TITLE
New Spiter-Anticheat

### ISSUE THREAD

**Issue by RegotlyLong** [ManInMyVan/Minecraft-Anticheat-List#6]
### Anticheat Name

Spiter Anticheat

### Cost

Premium

### Edition

Java

### Platform

Bukkit (or a fork)

### Status

Active (Recent updates, not explicitly inactive/unmaintained/discontinue)

### Versions

3.0 - b26

### Links

Github: https://github.com/RegotlyLong/SpiterAnticheat
Discord： https://discord.gg/TErzKwGUEc 

### Rating Percentage

100%

### Number of ratings

15

### Before submitting an anticheat

- [X] This anticheat wasn't already submitted (I have searched anticheat submitions on GitHub).

**Comment by ManInMyVan** [comment]
The version section is for Minecraft version, not plugin version

**Comment by RegotlyLong** [comment]
1.8-1.20.2

**Comment by RegotlyLong** [comment]
add web: https://bstats.org/plugin/bukkit/Spiter/19535
