### ISSUE TITLE
[New Anticheat] Anticheat

### ISSUE THREAD

**Issue by EclipsesDev** [ManInMyVan/Minecraft-Anticheat-List#9]
### Anticheat Name

Anticheat (yes that's the name of it)

### Cost

Free

### Platform

Bukkit (Java)

### Status

Old (Has not been updated recently, about 4 months)

### Minecraft Versions

Unknown (it support 1.7-1.8, more than that idk)

### Links

https://github.com/DemonDxv/Anticheat-Open-Source

https://www.spigotmc.org/resources/anticheat.93504/

### Before submitting an anticheat

- [X] This anticheat wasn't already submitted (I have searched anticheat submitions on GitHub).

**Comment by ManInMyVan** [comment]
[I already have this](https://github.com/ManInMyVan/Minecraft-Anticheat-List/blob/main/anticheats.json#L1065-L1083)

**Comment by EclipsesDev** [comment]
oh ok, didn't see that
